let data = [
    {
        title: 'Abcha Din Abcha Rat',
        artist: 'Rupak Tiary | Jakir  Aditya',
        genre: '',
        image: 'image/img1.jpg',
        audio: 'audio/Abcha Din Abcha Rat.mp3',
    },
    {
        title: 'Bondhu Tomay',
        artist: 'Rishi Panda | Chandrabindu',
        genre: '',
        image: 'image/img2.jpg',
        audio: 'audio/Bondhu Tomay.mp3',
    },
    {
        title: 'Hridoyer Rong',
        artist: 'Anupam Roy | Lagnajita',
        genre: '',
        image: 'image/img3.jpg',
        audio: 'audio/Hridoyer Rong.mp3',
    },
    {
        title: 'Kichchu Chaini Aami',
        artist: 'Rishi Panda',
        genre: '',
        image: 'image/img4.jpg',
        audio: 'audio/Kichchu Chaini Aami.mp3',
    },
    {
        title: 'O Bandhobi',
        artist: 'Rupak Tiary | Jayanta Roy',
        genre: '',
        image: 'image/img5.jpg',
        audio: 'audio/O Bandhobi.mp3',
    },
    {
        title: 'Prem Jeno Purno Holo',
        artist: 'Rupak Tiary | Trishna | Aditya Paul',
        genre: '',
        image: 'image/img6.jpg',
        audio: 'audio/Prem Jeno Purno Holo.mp3',
    },
    {
        title: 'Preme pora baron',
        artist: 'Rishi Panda',
        genre: '',
        image: 'image/img7.jpg',
        audio: 'audio/Preme pora baron.mp3',
    },
    {
        title: 'Shei Tumi',
        artist: 'Arko',
        genre: '',
        image: 'image/img8.jpg',
        audio: 'audio/Shei Tumi.mp3',
    },
    {
        title: 'Shona diya bandhayachi ghor',
        artist: 'Rishi Panda',
        genre: '',
        image: 'image/img9.jpg',
        audio: 'audio/Shona diya bandhayachi ghor.mp3',
    },
    {
        title: 'Shondhe Namar Aagey',
        artist: 'Ishan Mitra',
        genre: '',
        image: 'image/img10.jpg',
        audio: 'audio/Shondhe Namar Aagey.mp3',
    },
    {
        title: 'Takey Olpo Kachhe Dakchhi',
        artist: 'Rahul Dutta | Prem Tame ',
        genre: '',
        image: 'image/img11.jpg',
        audio: 'audio/Takey Olpo Kachhe Dakchhi.mp3',
    },
    {
        title: 'Opekkha',
        artist: 'The Bong Guy',
        genre: '',
        image: 'image/img12.jpg',
        audio: 'audio/Opekkha.mp3',
    },
    {
        title: 'Tomake',
        artist: 'Arko',
        genre: '',
        image: 'image/img13.jpg',
        audio: 'audio/Tomake.mp3',
    },
    {
        title: 'Tomake Na Lekha Chithita',
        artist: 'Sayiaan | Rupak Tiary | Jakir',
        genre: '',
        image: 'image/img14.jpg',
        audio: 'audio/Tomake Na Lekha Chithita.mp3',
    },
    {
        title: 'Tomar Kothay',
        artist: 'Rupak | Jakir',
        genre: '',
        image: 'image/img15.jpg',
        audio: 'audio/Tomar Kothay.mp3',
    },
    {
        title: 'Tomay Amay Mile',
        artist: 'Rupak Tiary',
        genre: '',
        image: 'image/img16.jpg',
        audio: 'audio/Tomay Amay Mile.mp3',
    },
    {
        title: 'Tomay hrid majhare rakhbo',
        artist: 'Borno Chakroborty',
        genre: '',
        image: 'image/img17.jpg',
        audio: 'audio/Tomay hrid majhare rakhbo.mp3',
    },
    {
        title: 'Tor Adorer Tane',
        artist: 'Rupak Tiary | Durba Banerjee',
        genre: '',
        image: 'image/img18.jpg',
        audio: 'audio/Tor Adorer Tane.mp3',
    },
    {
        title: 'Tor Name Lekha',
        artist: 'Rupak Tiary',
        genre: '',
        image: 'image/img19.jpg',
        audio: 'audio/Tor Name Lekha.mp3',
    },
    {
        title: 'Tumi Kothai',
        artist: 'Anupam Roy | Aziz Zaid',
        genre: '',
        image: 'image/img20.jpg',
        audio: 'audio/Tumi Kothai.mp3',
    },
    {
        title: 'Muskurane',
        artist: 'Arijit | Jeet',
        genre: '',
        image: 'image/img1.jpg',
        audio: 'audio/Muskurane.mp3',
    },
    {
        title: 'Banjaara',
        artist: 'Mohammed Irfan',
        genre: '',
        image: 'image/img2.jpg',
        audio: 'audio/Banjaara.mp3',
    },
    {
        title: 'Bekhayali',
        artist: 'Sachet Tandon',
        genre: '',
        image: 'image/img3.jpg',
        audio: 'audio/Bekhayali.mp3',
    },
    {
        title: 'Chahun Main Ya Naa',
        artist: 'Arijit | Palak',
        genre: '',
        image: 'image/img4.jpg',
        audio: 'audio/Chahun Main Ya Naa.mp3',
    },
    {
        title: 'Love Me Like You Do',
        artist: 'Ellie Goulding',
        genre: '',
        image: 'image/img5.jpg',
        audio: 'audio/Love Me Like You Do.mp3',
    },
    {
        title: 'E Tumi Kemon Tumi',
        artist: 'Rupankar',
        genre: '',
        image: 'image/img6.jpg',
        audio: 'audio/E Tumi Kemon Tumi.mp3',
    },
    {
        title: 'Haan Hasi Ban Gaye',
        artist: 'Shreya Ghoshal',
        genre: '',
        image: 'image/img7.jpg',
        audio: 'audio/Haan Hasi Ban Gaye.mp3',
    },
    {
        title: 'Hamdard',
        artist: 'Arijit Singh | Mithoon',
        genre: '',
        image: 'image/img8.jpg',
        audio: 'audio/Hamdard.mp3',
    },
    {
        title: 'Jogi',
        artist: 'Yasser | Aakanksha',
        genre: '',
        image: 'image/img9.jpg',
        audio: 'audio/Jogi.mp3',
    },
    {
        title: 'Kaun Tujhe',
        artist: 'Amaal Mallik | Palak',
        genre: '',
        image: 'image/img10.jpg',
        audio: 'audio/Kaun Tujhe.mp3',
    },
    {
        title: 'Tera Ban Jaunga',
        artist: 'Tulsi Kumar | Akhil Sachdeva',
        genre: '',
        image: 'image/img11.jpg',
        audio: 'audio/Tera Ban Jaunga.mp3',
    },
    {
        title: 'Tujhe Kitna Chahne Lage',
        artist: 'Mithoon | Arijit Singh',
        genre: '',
        image: 'image/img12.jpg',
        audio: 'audio/Tujhe Kitna Chahne Lage.mp3',
    },
    {
        title: 'One More Light',
        artist: 'Linkin Park',
        genre: '',
        image: 'image/img13.jpg',
        audio: 'audio/One More Light.mp3',
    },
    {
        title: 'Main Jis Din Bhulaa Du',
        artist: 'Rochak | Jubin | Tulsi ',
        genre: '',
        image: 'image/img14.jpg',
        audio: 'audio/Main Jis Din Bhulaa Du.mp3',
    },
    {
        title: 'Main Rahoon Ya Na Rahoon',
        artist: 'Amaal | Armaan',
        genre: '',
        image: 'image/img15.jpg',
        audio: 'audio/Main Rahoon Ya Na Rahoon.mp3',
    },
    {
        title: 'Radha',
        artist: 'Iman | Shovan',
        genre: '',
        image: 'image/img16.jpg',
        audio: 'audio/Radha.mp3',
    },
    {
        title: 'Soch Na Sake',
        artist: 'Arijit Singh | Tulsi Kumar',
        genre: '',
        image: 'image/img17.jpg',
        audio: 'audio/Soch Na Sake.mp3',
    },
];
